### ISSUE TITLE
Missing a license

### ISSUE THREAD

**Issue by kyusu** [hamsterbacke23/movierater#2]
H Tobi,

I've just discovered that your project does not have license. 😿 
Could you maybe pick one?

Greetings from Stuttgart
Christian

**Comment by hamsterbacke23** [comment]
Thanks, closed with https://github.com/hamsterbacke23/movierater/commit/3e36f75c0faa41f2be91ce3ce89227cef0c58464

**Comment by kyusu** [comment]
Cool!
